packages:
  - apps/*
  - scripts/*
  - packages/*
  - api
  - docs
  - backend
catalog:
  '@biomejs/biome': ^1.9.4
  '@changesets/cli': ^2.29.4
  '@clack/prompts': ^0.10.1
  '@manypkg/get-packages': ^3.0.0
  '@rsbuild/core': ^1.3.22
  '@rsbuild/plugin-vue': ^1.0.7
  '@tailwindcss/postcss': ^4.1.8
  '@types/node': ^22.15.29
  '@vite-pwa/vitepress': ^1.0.0
  '@vueuse/core': ^13.3.0
  cac: ^6.7.14
  chalk: ^5.4.1
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  consola: ^3.4.2
  execa: ^9.6.0
  find-up: ^7.0.0
  lucide-vue-next: ^0.508.0
  markdown-it-custom-attrs: ^1.0.2
  minimatch: ^10.0.1
  postcss: ^8.5.4
  reka-ui: ^2.3.0
  tailwind-merge: ^3.3.0
  tailwindcss: ^4.1.8
  turbo: ^2.5.4
  tw-animate-css: ^1.3.3
  typescript: ^5.8.3
  unbuild: ^3.5.0
  vitepress: ^1.6.3
  vue: ^3.5.16
  vue-i18n: ^11.1.5
  vue-router: ^4.5.1
  vue-sonner: ^1.3.2
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@nestjs/core'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - vue-demi
