packages:
  - apps/*
  - scripts/*
  - packages/*
  - api
  - docs
  - backend
onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@nestjs/core"
  - "@scarf/scarf"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - core-js
  - esbuild
  - vue-demi
catalog:
  "@biomejs/biome": ^1.9.4
  "@changesets/cli": ^2.29.4
  "@clack/prompts": ^0.10.1
  "@dataui/crud": ^5.3.4
  "@dataui/crud-typeorm": ^5.3.4
  "@eslint/eslintrc": ^3.3.1
  "@eslint/js": ^9.28.0
  "@manypkg/get-packages": ^3.0.0
  "@nestjs/cli": ^11.0.7
  "@nestjs/common": ^11.1.3
  "@nestjs/core": ^11.1.3
  "@nestjs/platform-express": ^11.1.3
  "@nestjs/schematics": ^11.0.5
  "@nestjs/swagger": ^11.2.0
  "@nestjs/testing": ^11.1.3
  "@nestjs/typeorm": ^11.0.0
  "@rsbuild/core": ^1.3.22
  "@rsbuild/plugin-image-compress": ^1.2.0
  "@rsbuild/plugin-vue": ^1.0.7
  "@swc/cli": ^0.6.0
  "@swc/core": ^1.12.0
  "@tailwindcss/postcss": ^4.1.8
  "@tanstack/vue-table": ^8.21.3
  "@types/express": ^5.0.3
  "@types/jest": ^29.5.14
  "@types/node": ^22.15.31
  "@types/supertest": ^6.0.3
  "@vite-pwa/vitepress": ^1.0.0
  "@vueuse/core": 13.3.0
  axios: ^1.9.0
  cac: ^6.7.14
  chalk: ^5.4.1
  class-transformer: ^0.5.1
  class-validator: ^0.14.2
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  consola: ^3.4.2
  cross-env: ^7.0.3
  eslint: ^9.28.0
  eslint-config-prettier: ^10.1.5
  eslint-plugin-prettier: ^5.4.1
  execa: ^9.6.0
  express: ^5.1.0
  find-up: ^7.0.0
  globals: ^16.2.0
  http-proxy-middleware: ^3.0.5
  jest: ^29.7.0
  lucide-vue-next: ^0.508.0
  markdown-it-custom-attrs: ^1.0.2
  minimatch: ^10.0.1
  mysql: ^2.18.1
  pinia: ^3.0.3
  postcss: ^8.5.4
  prettier: ^3.5.3
  reflect-metadata: ^0.2.2
  reka-ui: ^2.3.1
  rxjs: ^7.8.2
  source-map-support: ^0.5.21
  supertest: ^7.1.1
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.8
  topbar: ^3.0.0
  ts-jest: ^29.3.4
  ts-loader: ^9.5.2
  ts-node: ^10.9.2
  tsconfig-paths: ^4.2.0
  turbo: ^2.5.4
  tw-animate-css: ^1.3.4
  typeorm: ^0.3.24
  typescript: ^5.8.3
  typescript-eslint: ^8.34.0
  unbuild: ^3.5.0
  vitepress: ^1.6.3
  vue: 3.5.16
  vue-i18n: ^11.1.5
  vue-router: ^4.5.1
  vue-sonner: ^1.3.2
