packages:
  - apps/*
  - scripts/*
  - packages/*
  - docs
  - backend
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - vue-demi

catalog:
  "@biomejs/biome": "^1.9.4"
  "@rsbuild/core": "^1.3.15"
  "@rsbuild/plugin-vue": "^1.0.7"
  "@types/node": "^22.15.3"
  "@vue/tsconfig": "^0.7.0"
  "@clack/prompts": "^0.10.1"
  "@vueuse/core": "^13.2.0"
  "@manypkg/get-packages": "^3.0.0"
  "@tailwindcss/postcss": "^4.1.5"
  "postcss": "^8.5.3"
  "tailwindcss": "^4.1.7"
  "tw-animate-css": "^1.2.9"
  "tailwind-merge": "^3.2.0"
  "turbo": "^2.5.3"
  "typescript": "^5.8.3"
  "unbuild": "^3.5.0"
  "cac": "^6.7.14"
  "chalk": "^5.4.1"
  "consola": "^3.4.2"
  "execa": "^9.5.2"
  "find-up": "^7.0.0"
  "vue": "^3.5.14"
  "vue-i18n": "^11.1.3"
  "vue-router": "^4.5.1"
  "vue-sonner": "^1.3.2"
  "class-variance-authority": "^0.7.1"
  "lucide-vue-next": "^0.508.0"
  "reka-ui": "^2.2.1"
  "clsx": "^2.1.1"